FROM mcr.microsoft.com/dotnet/sdk:10.0 AS build
WORKDIR /src

COPY src/Medications.Api/Medications.Api.csproj src/Medications.Api/
RUN dotnet restore src/Medications.Api/Medications.Api.csproj

COPY . .
WORKDIR /src/src/Medications.Api
RUN dotnet publish -c Release -o /app/publish

FROM mcr.microsoft.com/dotnet/aspnet:10.0 AS final
WORKDIR /app
COPY --from=build /app/publish .
EXPOSE 8080
ENTRYPOINT ["dotnet", "Medications.Api.dll"]
